# Generated by Django 6.0.3 on 2026-03-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reliability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_rate', models.FloatField(default=100.0)),
                ('cancellation_count', models.IntegerField(default=0)),
                ('no_show_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('complaint_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('restriction_count', models.IntegerField(default=0)),
                ('trust_score', models.FloatField(default=100.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('fake_listing', 'Fake Listing'), ('no_show', 'No Show'), ('late', 'Late'), ('cancellation', 'Cancellation'), ('bad_quality', 'Bad Quality'), ('abuse', 'Abuse/Spam')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('action_taken', models.CharField(choices=[('warning', 'Warning'), ('temp_limit', 'Temporary Limit'), ('restricted', 'Restricted'), ('review', 'Needs Review')], default='warning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
