# Generated by Django 6.0.3 on 2026-03-28 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('food_category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('is_veg', models.BooleanField(default=True)),
                ('prepared_at', models.DateTimeField()),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('urgency_score', models.FloatField(default=0)),
                ('quality_risk', models.CharField(default='low', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
